on:
  workflow_dispatch:
  push:
    branches: [main, master]
  # pull_request:
  #   branches: [main, master]

name: Quarto Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      
      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::knitr
            any::rmarkdown
            any::palmerpenguins
            any::tidyr
            any::dplyr
            any::sf
            any::ggplot2
            any::unmarked
            any::posterior
            any::checkmate
            any::data.table
            any::processx
            any::here

      - name: Cache CmdStan
        uses: actions/cache@v4
        with:
          path: ~/.cmdstan
          key: cmdstan-${{ runner.os }}-v2

      - name: Install cmdstanr
        run: |
          Rscript -e 'install.packages("cmdstanr", repos="https://mc-stan.org/r-packages/")'

      - name: Install CmdStan
        run: |
          Rscript -e 'cmdstanr::install_cmdstan(cores = 2)'

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
